
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sabda
 */
public class crud extends javax.swing.JFrame {
   DefaultTableModel model;
   
    public crud() {
        initComponents();
        String []judul={"ID","NAMA","ALAMAT","PEKERJAAN"};
        model = new DefaultTableModel(judul,0);
        jt.setModel(model);
        tampilkan();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_pekerjaan = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        txt_cari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_alamat = new javax.swing.JTextArea();
        btn_hapus = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        btn_ganti = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt = new javax.swing.JTable();
        txt_nama = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Anggota");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Pekerjaan : ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ID : ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Nama : ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Alamat : ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));
        jPanel2.add(txt_pekerjaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 140, -1));
        jPanel2.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 140, -1));
        jPanel2.add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 140, -1));

        txt_alamat.setColumns(20);
        txt_alamat.setRows(5);
        jScrollPane1.setViewportView(txt_alamat);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 180, 80));

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel2.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 70, -1));

        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        jPanel2.add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, -1));

        btn_ganti.setText("Ganti");
        btn_ganti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gantiActionPerformed(evt);
            }
        });
        jPanel2.add(btn_ganti, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 70, -1));

        jt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jt);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 500, 90));
        jPanel2.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 140, -1));

        btn_cari.setText("Cari");
        jPanel2.add(btn_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 520, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
       try {
           Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/latihan","root","");
           int executeUpdate = koneksi.createStatement().executeUpdate("insert into latihan_crud values"+"('"+txt_id.getText()+"','"+txt_nama.getText()+"','"+txt_alamat.getText()+"','"+txt_pekerjaan.getText()+"')");
           tampilkan();
           reset();
       } catch (SQLException ex) {
           Logger.getLogger(crud.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_gantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gantiActionPerformed
       try {
           Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/latihan","root","");
           int executeUpdate = koneksi.createStatement().executeUpdate("update latihan_crud set nama='"+txt_nama.getText()+"',alamat='"+txt_alamat.getText()+"',pekerjaan='"+txt_pekerjaan.getText()+"' where id_anggota='"+txt_id.getText()+"'");
           tampilkan();
           reset();
       } catch (SQLException ex) {
           Logger.getLogger(crud.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_btn_gantiActionPerformed

    private void jtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtMouseClicked
        int i = jt.getSelectedRow();
        if(i>-1){
            txt_id.setText(model.getValueAt(i, 0).toString());
            txt_nama.setText(model.getValueAt(i, 1).toString());
            txt_pekerjaan.setText(model.getValueAt(i, 3).toString());
            txt_alamat.setText(model.getValueAt(i, 2).toString());
        }
    }//GEN-LAST:event_jtMouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
       try {
           Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/latihan","root","");
           koneksi.createStatement().executeUpdate("delet from latihan_crud where id_anggota='"+txt_id.getText()+"'");
           tampilkan();
           reset();
       } catch (SQLException ex) {
           Logger.getLogger(crud.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_btn_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_ganti;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jt;
    private javax.swing.JTextArea txt_alamat;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_pekerjaan;
    // End of variables declaration//GEN-END:variables

    private void tampilkan() {
        int row =jt.getRowCount();
        for(int i=0;i<row;i++)
        {
            model.removeRow(0);
        }
       try {
           Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/latihan","root","");
           ResultSet rs = koneksi.createStatement().executeQuery("SELECT * FROM latihan_crud");
           while (rs.next())
           {
               String data[]={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)};
               model.addRow(data);
           }
       } catch (SQLException ex) {
           Logger.getLogger(crud.class.getName()).log(Level.SEVERE, null, ex);
       }
    }
    private void reset()
    {
        txt_id.setText("");
        txt_nama.setText("");
        txt_pekerjaan.setText("");
        txt_alamat.setText("");
        
    }
}
